# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Title of your Website
title: Xiangping Lin

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL: 'https://example.com/' # Website URL

############################
## LANGUAGE
############################

# Default language to use (if you setup multilingual support)
defaultContentLanguage: en
hasCJKLanguage: false # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

############################
## Advanced options below ##
############################

# Get last modified date for content from Git?
enableGitInfo: true

summaryLength: 30

paginate: 10 # Number of items per page in paginated lists.

enableEmoji: true

enableRobotsTXT: true

footnotereturnlinkcontents: <sup>^</sup>

ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]

permalinks:
  event: '/talk/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'

disableAliases: true

outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart # Anchor for cropping. Options include Smart and Center.

timeout: 600000

taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors

markup:
  _merge: deep

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70

security:
  _merge: deep

sitemap:
  _merge: deep
