# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance, 
# Fonts 
# You can choose from one of the following built-in font sets or create your own font set with Google Fonts or your own font files: 
# Minimal (modern) 
# Classic (original Academic v1 style) 
# Rose (traditional serif) 
# Mr Robot (futuristic) 
# Cyberpunk (hacker style) 
# Native: use device fonts for maximum performance 
# To choose a font set, set the font option in config/_default/params.yaml. 
# Font Sizes The font size can be changed all the way from extra-small to extra large using the font_size option in config/_default/params.yaml. 
# Supported font sizes are xs, s, m, l, xl.

 appearance:
  theme_day: "minimal"
  theme_night: "minimal"
# font: minimal
  font: Mr Robot
  font_size: M

# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

# Color theme.
#   Choose from `default`, `ocean`, `forest`, `dark`, `apogee`, `1950s`, `coffee`, `cupcake`.
# color_theme = "default"

# Enable users to switch between day and night mode?
# day_night = true

# Font style.
#   Choose from `default`, `classic`, or `playfair`.
# font = "default"

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Xiangping Lin website'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
